project_id = "pyizjlioocxfjvnosxqy"

[functions.request-wapi-credentials]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.send-appointment-reminders]
verify_jwt = false

[functions.send-daily-agenda]
verify_jwt = false

[functions.send-barber-invite]
verify_jwt = false

[functions.create-mercadopago-preference]
verify_jwt = true

[functions.mercadopago-webhook]
verify_jwt = false
